### ISSUE TITLE
Rivet-buildplugin - not able to compile plugin (lxplus), relocation issue

### ISSUE THREAD

**Issue by maireiphc** [alisw/rivet#6]
Trying the newly deployed AliGenerators bundle ([AliGenerators::v20200323-1](http://alimonitor.cern.ch/packages/#VO_ALICE@AliGenerators::v20200323-1)), I still face issues under lxplus on the Rivet front with rivet-buildplugin:
It does not work under lxplus (cgal libs not found) but a compilation under alidock from master alidist of yesterday (normally equivalent to AliGenerators::v20200323-1), there it works.
See below.

I am unsure about what should be modified under : https://github.com/alisw/rivet/blob/alice/2.7.2/bin/rivet-buildplugin.in
Breaking down the printout from the command, the main difference is coming in the lxplus lines : 

```
-L/build/workarea/sw/20156114/1/slc6_x86-64/cgal/4.6.3-16/lib 
-Wl,-rpath,/build/workarea/sw/20156114/1/slc6_x86-64/cgal/4.6.3-16/lib 
-L/build/workarea/sw/20156114/1/slc6_x86-64/GMP/v6.0.0-34/lib 
-Wl,-rpath,/build/workarea/sw/20156114/1/slc6_x86-64/GMP/v6.0.0-34/lib 
```
which apparently points to a **relocation problem** of env variables between build system and the execution system...

Any clue where to start the debugging from ?

Antonin

----

Under lxplus (CentOS Linux release 7.7.1908) : _FAILING_

```
/cvmfs/alice.cern.ch/bin/alienv enter  VO_ALICE@AliGenerators::v20200323-1

10 -lxplus776: SandBox-RivetMC >rivet-buildplugin ALICE_2017_I1511870.cc
Using default library name 'RivetAnalysis.so'
/cvmfs/alice.cern.ch/el7-x86_64/Packages/GCC-Toolchain/v7.3.0-alice1-9/bin/g++ -o "RivetAnalysis.so" -shared -fPIC  -I/cvmfs/alice.cern.ch/el6-x86_64/Packages/Rivet/2.7.2-alice8-1/include -I/cvmfs/alice.cern.ch/el6-x86_64/Packages/HepMC/HEPMC_02_06_10-4/include -I/cvmfs/alice.cern.ch/el6-x86_64/Packages/YODA/v1.7.4-18/include -I/cvmfs/alice.cern.ch/el6-x86_64/Packages/fastjet/v3.3.3_1.042-alice1-1/include -I/cvmfs/alice.cern.ch/el6-x86_64/Packages/GSL/v1.16-36/include   -pedantic -Wall -Wno-long-long -Wno-format -Werror=uninitialized -Werror=delete-non-virtual-dtor -fopenmp -std=c++11   -Wl,--no-as-needed  -L/cvmfs/alice.cern.ch/el6-x86_64/Packages/Rivet/2.7.2-alice8-1/lib -L/cvmfs/alice.cern.ch/el6-x86_64/Packages/HepMC/HEPMC_02_06_10-4/lib -L/cvmfs/alice.cern.ch/el6-x86_64/Packages/YODA/v1.7.4-18/lib   -Wl,-rpath,/cvmfs/alice.cern.ch/el6-x86_64/Packages/fastjet/v3.3.3_1.042-alice1-1/lib -L/cvmfs/alice.cern.ch/el6-x86_64/Packages/fastjet/v3.3.3_1.042-alice1-1/lib -lfastjettools -lfastjet -lCGAL -lgmp -L/build/workarea/sw/20156114/1/slc6_x86-64/cgal/4.6.3-16/lib -Wl,-rpath,/build/workarea/sw/20156114/1/slc6_x86-64/cgal/4.6.3-16/lib -L/build/workarea/sw/20156114/1/slc6_x86-64/GMP/v6.0.0-34/lib -Wl,-rpath,/build/workarea/sw/20156114/1/slc6_x86-64/GMP/v6.0.0-34/lib -lm -lfastjetplugins -lsiscone_spherical -lsiscone  -lRivet    ALICE_2017_I1511870.cc
/cvmfs/alice.cern.ch/el7-x86_64/Packages/GCC-Toolchain/v7.3.0-alice1-9/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lCGAL
collect2: error: ld returned 1 exit status
make: *** [RivetAnalysis.so] Erreur 1
```

under alidock (CentOS Linux release 7.6.1810) : _SUCCESSFUL_

```
3 -alidock-7111: ~ >alienv load VO_ALICE@AliGenerators::v20200323-1
Use alienv list to list loaded modules.
..
6 -alidock-7111: tempTest >rivet-buildplugin RivetALICE_2015_I1357424.so ALICE_2015_I1357424.cc
/home/alidock/.sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice1-14/bin/g++ -o "RivetALICE_2015_I1357424.so" -shared -fPIC  -I/home/alidock/.sw/slc7_x86-64/Rivet/2.7.2-alice8-1/include -I/home/alidock/.sw/slc7_x86-64/HepMC/HEPMC_02_06_10-1/include -I/home/alidock/.sw/slc7_x86-64/YODA/v1.7.4-2/include -I/home/alidock/.sw/slc7_x86-64/fastjet/v3.3.3_1.042-alice1-1/include -I/home/alidock/.sw/slc7_x86-64/GSL/v1.16-41/include   -pedantic -Wall -Wno-long-long -Wno-format -Werror=uninitialized -Werror=delete-non-virtual-dtor -fopenmp -std=c++11   -Wl,--no-as-needed  -L/home/alidock/.sw/slc7_x86-64/Rivet/2.7.2-alice8-1/lib -L/home/alidock/.sw/slc7_x86-64/HepMC/HEPMC_02_06_10-1/lib -L/home/alidock/.sw/slc7_x86-64/YODA/v1.7.4-2/lib   -Wl,-rpath,/home/alidock/.sw/slc7_x86-64/fastjet/v3.3.3_1.042-alice1-1/lib -L/home/alidock/.sw/slc7_x86-64/fastjet/v3.3.3_1.042-alice1-1/lib -lfastjettools -lfastjet -lCGAL -lgmp -L/home/alidock/.sw/slc7_x86-64/cgal/4.6.3-1/lib -Wl,-rpath,/home/alidock/.sw/slc7_x86-64/cgal/4.6.3-1/lib -L/home/alidock/.sw/slc7_x86-64/GMP/v6.0.0-46/lib -Wl,-rpath,/home/alidock/.sw/slc7_x86-64/GMP/v6.0.0-46/lib -lm -lfastjetplugins -lsiscone_spherical -lsiscone  -lRivet    ALICE_2015_I1357424.cc
7 -alidock-7111: tempTest >ll
-rwxr-xr-x 1 userMe users 1.1M Mar 24 13:57 RivetALICE_2015_I1357424.so*
```

**Comment by qgp** [comment]
@maireiphc Can you have a look at the line corresponding to https://github.com/alisw/rivet/blob/093909b9d3fdc509b4c022b93f7ae109f51dd136/bin/rivet-buildplugin.in#L189 in `rivet-buildplugin` on lxplus? Maybe the env variables were resolved at build time already?

**Comment by maireiphc** [comment]
Under lxplus : 
`>which rivet-buildplugin`
/cvmfs/alice.cern.ch/el6-x86_64/Packages/Rivet/2.7.2-alice8-1/bin/rivet-buildplugin
 `>grep lfastjet /cvmfs/alice.cern.ch/el6-x86_64/Packages/Rivet/2.7.2-alice8-1/bin/rivet-buildplugin`
lfastjet="${CGAL_ROOT:+-L$CGAL_ROOT/lib} ${GMP_ROOT:+-L$GMP_ROOT/lib} $(fastjet-config --plugins --shared --libs)"

So the line seem to be untouched compared to the RIVET source rivet/bin/rivet-buildplugin.in
On the other hand, env var like GMP_ROOT and CGAL_ROOT remains unknown under the same current lxplus session.

**Comment by qgp** [comment]
In fact, `CGAL_ROOT` was removed as environment variables in https://github.com/alisw/alidist/commit/3a41f33a8ab95be2ea23afc5b2a84ee9a48a865a
As there are also no other environment variables, we have no way of knowing where to take the libs from. GMP is simply missing as a dependency (only build_required) and, thus, the package is not loaded.

@ktf I think we need some variable exported for CGAL. If you don't want to have `<PKGNAME>_ROOT` could you propose something better?

**Comment by preghenella** [comment]
hello @maireiphc @qgp @ktf 
what is the status here?
is it not sufficient to add
```
setenv CGAL_ROOT \$CGAL_ROOT
```
in `cgal.sh` receipt to proceed?

I have opened a PR in `alidist` for that
https://github.com/alisw/alidist/pull/2166

Please, let me know if this is not ok.

Cheers,
Roberto

**Comment by preghenella** [comment]
ps: `GMP_ROOT` seems to be exported in `gmp.sh`.
Reading again the comment from @qgp , the issue with GPM is a missing dependency.
But, should the dependency be in `cgal.sh` or should we put it the `rivet.sh` receipt?

It sounds to be perhaps more appropriate to have it as a dependency in `rivet.sh` if this is the actual place where the lib is needed at run time. But I might be wrong.

**Comment by ktf** [comment]
CGAL_ROOT as runtime variable is not exported by any cgal installation, so I'd rather avoid it. This is to allow picking it up from the system. Given only fastjet needs it, how about changing cgal and gmp as build requires and copying the libraries inside the fastjet lib folder?

**Comment by preghenella** [comment]
If I understand correctly, the issue is that `rivet-buildplugin` relies on CGAL_ROOT and GMP_ROOT variables.
This was reported by @maireiphc 
```
grep lfastjet /cvmfs/alice.cern.ch/el6-x86_64/Packages/Rivet/2.7.2-alice8-1/bin/rivet-buildplugin
lfastjet="${CGAL_ROOT:+-L$CGAL_ROOT/lib} ${GMP_ROOT:+-L$GMP_ROOT/lib} $(fastjet-config --plugins --shared --libs)"
```

So, I think the issue happens when there is no CGAL on the system and CGAL built by `aliBuild` has to be used. In this case `rivet-buildplugin` does not know where to go to fish the library.
It looks to me like, if CGAL_ROOT is not defined it will pick it from the system. Otherwise it will pick it from the CGAL_ROOT location. 

Am I getting it wrong?

**Comment by qgp** [comment]
> CGAL_ROOT as runtime variable is not exported by any cgal installation, so I'd rather avoid it. This is to allow picking it up from the system. Given only fastjet needs it, how about changing cgal and gmp as build requires and copying the libraries inside the fastjet lib folder?

@ktf But by now <PKG>_ROOT is at least considered a default search location for packages by cmake. I am not very fond of copying over libraries to fastjet which then essentially hides the fact that those packages are even being used (seems much hackier to me than having an additional environment variable).

**Comment by ktf** [comment]
Yes, but cmake is used for building, and indeed there we do export (automatically) all the relevant _ROOT variable. On the other hand, there is no distribution of CGal which export CGAL_ROOT as a runtime variable, so this will work only with alibuild provided packages. That would be an additional problem if cgal, which after all is not such an uncommon package, is also installed from the system. IMHO, the correct solution is either copying them or (even better) making them archive libraries (we are talking about less than 1MB of binaries, BTW).

**Comment by qgp** [comment]
@ktf Ok, this would be clean if it truly was a build dependency only. Having said that, I have never verified which part of CGAL/GMP is actually exposed by fastjet, i.e. why a package using fastjet needs to explicitly link against those libs at all (always took this for granted as `fastjet-config --libs` reports those libraries), but maybe worth double-checking.

**Comment by preghenella** [comment]
This issue should be resolved by https://github.com/alisw/alidist/pull/2166.
`CGAL_ROOT` environment variable is now set.
@maireiphc , would you mind please check all is fine and close in case?

Thanks

**Comment by qgp** [comment]
@preghenella @maireiphc Is this still an issue?

**Comment by preghenella** [comment]
in principle it should not be. But I myself did not check.

**Comment by maireiphc** [comment]
Hi @qgp , (all),

likely yes, the issue is still indirectly there, since the fix proposed by Roberto came after the last deployment of packages to CVMFS 
http://alimonitor.cern.ch/packages/?#VO_ALICE@AliGenerators::v20200409-1
i.e. 
in the meantime, @ktf switched the build system from slc6 to slc7/CC7 (due to other issues) but such builds are not yet deployed to CVMFS (need to tamper with alibot as far as I got).

**Comment by qgp** [comment]
@maireiphc Are you saying we should wait for the deployment of the CC7 builds to cvmfs in order to check?

**Comment by preghenella** [comment]
CC7 deployment was tested and fine.
Closing.
